new Vue({
  el: '#app',
  data: {
    showButton: true,
    showProgress: false,
        
      images: [
        { src: "/first try/img/second.jpg", text: "Text preV dejepise sa menuje rovina Mohy pri Šajave, na ktorej sa tá bitka stala, a že na dolnej Šajave v Gemeri, neďaleko Šajo-Gemera, nachodí sa osada Méhi, ktorá s týmže menom má velikú podobnosť, a že tam na rovine sú aj značné pahŕbky plné umrlčích kostí, znakom velikej tam niekdy svedenej bitky: preto daktorí dejepisci túto bitku s Tatármi do Gemera ku osade Méhi kladú. Medzi tým, keď všetky okolnosti tej bitky dobre povážime, ako Tatári roku 5. panovania kráľa Belu, nasledovne už r. 1240 pod vedením Batu čili Batena v sile 500.000 vojska z ruskej zeme vtrhli do Uhár a najprv síce na hlavu porazili palatína, strážiaceho hranice 12. marca a všetko jeho vojsko strelami a mečmi pobili, ženúc sa prosto ku Pešti. Keď ale kráľ Bela so svojím nanáhle shromaždeným vojskom vytiahnul z Pešti, vtedy Tatári ustupovali nazpät, pritiahnuc k sebe všetky svoje roztratené čaty, až ku rieke Šajave, kde cez stojáci most prešli na druhú stranu rieky a tam sa potom na rovine zastavili a do boja pripravili; keď toto všetko povážime, tedy to predsa nie pri osade Méhi, kde je rieka Šajava ešte nepatrná a dá sa ľahko prebrodiť, ale pri Onóde, neďaleko vtoku Šajave do Tisy, kde je rieka táto — súc spojená s Rimavou a Hornadom — hodne široká, udať sa muselo. Krem toho z Pešti nazpät ku Onódu cez Jáger bola im rovná, otvorená a ích tlupami všade obsadená cesta. Tam pri Onóde sa nachodily aj veliké močariny, ktoré na jar rozvodnená Tisa a Šajava robievala, ajok 1" },
        { src: "/first try/img/moto.jpg", text: "Text pre oV dejepise sa menuje rovina Mohy pri Šajave, na ktorej sa tá bitka stala, a že na dolnej Šajave v Gemeri, neďaleko Šajo-Gemera, nachodí sa osada Méhi, ktorá s týmže menom má velikú podobnosť, a že tam na rovine sú aj značné pahŕbky plné umrlčích kostí, znakom velikej tam niekdy svedenej bitky: preto daktorí dejepisci túto bitku s Tatármi do Gemera ku osade Méhi kladú. Medzi tým, keď všetky okolnosti tej bitky dobre povážime, ako Tatári roku 5. panovania kráľa Belu, nasledovne už r. 1240 pod vedením Batu čili Batena v sile 500.000 vojska z ruskej zeme vtrhli do Uhár a najprv síce na hlavu porazili palatína, strážiaceho hranice 12. marca a všetko jeho vojsko strelami a mečmi pobili, ženúc sa prosto ku Pešti. Keď ale kráľ Bela so svojím nanáhle shromaždeným vojskom vytiahnul z Pešti, vtedy Tatári ustupovali nazpät, pritiahnuc k sebe všetky svoje roztratené čaty, až ku rieke Šajave, kde cez stojáci most prešli na druhú stranu rieky a tam sa potom na rovine zastavili a do boja pripravili; keď toto všetko povážime, tedy to predsa nie pri osade Méhi, kde je rieka Šajava ešte nepatrná a dá sa ľahko prebrodiť, ale pri Onóde, neďaleko vtoku Šajave do Tisy, kde je rieka táto — súc spojená s Rimavou a Hornadom — hodne široká, udať sa muselo. Krem toho z Pešti nazpät ku Onódu cez Jáger bola im rovná, otvorená a ích tlupami všade obsadená cesta. Tam pri Onóde sa nachodily aj veliké močariny, ktoré na jar rozvodnená Tisa a Šajava robievala, aj 2" },
        { src: "/first try/img/hochsch.jpg", text: "Text prV dejepise sa menuje rovina Mohy pri Šajave, na ktorej sa tá bitka stala, a že na dolnej Šajave v Gemeri, neďaleko Šajo-Gemera, nachodí sa osada Méhi, ktorá s týmže menom má velikú podobnosť, a že tam na rovine sú aj značné pahŕbky plné umrlčích kostí, znakom velikej tam niekdy svedenej bitky: preto daktorí dejepisci túto bitku s Tatármi do Gemera ku osade Méhi kladú. Medzi tým, keď všetky okolnosti tej bitky dobre povážime, ako Tatári roku 5. panovania kráľa Belu, nasledovne už r. 1240 pod vedením Batu čili Batena v sile 500.000 vojska z ruskej zeme vtrhli do Uhár a najprv síce na hlavu porazili palatína, strážiaceho hranice 12. marca a všetko jeho vojsko strelami a mečmi pobili, ženúc sa prosto ku Pešti. Keď ale kráľ Bela so svojím nanáhle shromaždeným vojskom vytiahnul z Pešti, vtedy Tatári ustupovali nazpät, pritiahnuc k sebe všetky svoje roztratené čaty, až ku rieke Šajave, kde cez stojáci most prešli na druhú stranu rieky a tam sa potom na rovine zastavili a do boja pripravili; keď toto všetko povážime, tedy to predsa nie pri osade Méhi, kde je rieka Šajava ešte nepatrná a dá sa ľahko prebrodiť, ale pri Onóde, neďaleko vtoku Šajave do Tisy, kde je rieka táto — súc spojená s Rimavou a Hornadom — hodne široká, udať sa muselo. Krem toho z Pešti nazpät ku Onódu cez Jáger bola im rovná, otvorená a ích tlupami všade obsadená cesta. Tam pri Onóde sa nachodily aj veliké močariny, ktoré na jar rozvodnená Tisa a Šajava robievala, ajzok 3" },
        { src: "/first try/img/kenn.jpg", text: "Text pre oV dejepise sa menuje rovina Mohy pri Šajave, na ktorej sa tá bitka stala, a že na dolnej Šajave v Gemeri, neďaleko Šajo-Gemera, nachodí sa osada Méhi, ktorá s týmže menom má velikú podobnosť, a že tam na rovine sú aj značné pahŕbky plné umrlčích kostí, znakom velikej tam niekdy svedenej bitky: preto daktorí dejepisci túto bitku s Tatármi do Gemera ku osade Méhi kladú. Medzi tým, keď všetky okolnosti tej bitky dobre povážime, ako Tatári roku 5. panovania kráľa Belu, nasledovne už r. 1240 pod vedením Batu čili Batena v sile 500.000 vojska z ruskej zeme vtrhli do Uhár a najprv síce na hlavu porazili palatína, strážiaceho hranice 12. marca a všetko jeho vojsko strelami a mečmi pobili, ženúc sa prosto ku Pešti. Keď ale kráľ Bela so svojím nanáhle shromaždeným vojskom vytiahnul z Pešti, vtedy Tatári ustupovali nazpät, pritiahnuc k sebe všetky svoje roztratené čaty, až ku rieke Šajave, kde cez stojáci most prešli na druhú stranu rieky a tam sa potom na rovine zastavili a do boja pripravili; keď toto všetko povážime, tedy to predsa nie pri osade Méhi, kde je rieka Šajava ešte nepatrná a dá sa ľahko prebrodiť, ale pri Onóde, neďaleko vtoku Šajave do Tisy, kde je rieka táto — súc spojená s Rimavou a Hornadom — hodne široká, udať sa muselo. Krem toho z Pešti nazpät ku Onódu cez Jáger bola im rovná, otvorená a ích tlupami všade obsadená cesta. Tam pri Onóde sa nachodily aj veliké močariny, ktoré na jar rozvodnená Tisa a Šajava robievala, aj 4" },
        { src: "/first try/img/pb.png", text: "Text pre obrV dejepise sa menuje rovina Mohy pri Šajave, na ktorej sa tá bitka stala, a že na dolnej Šajave v Gemeri, neďaleko Šajo-Gemera, nachodí sa osada Méhi, ktorá s týmže menom má velikú podobnosť, a že tam na rovine sú aj značné pahŕbky plné umrlčích kostí, znakom velikej tam niekdy svedenej bitky: preto daktorí dejepisci túto bitku s Tatármi do Gemera ku osade Méhi kladú. Medzi tým, keď všetky okolnosti tej bitky dobre povážime, ako Tatári roku 5. panovania kráľa Belu, nasledovne už r. 1240 pod vedením Batu čili Batena v sile 500.000 vojska z ruskej zeme vtrhli do Uhár a najprv síce na hlavu porazili palatína, strážiaceho hranice 12. marca a všetko jeho vojsko strelami a mečmi pobili, ženúc sa prosto ku Pešti. Keď ale kráľ Bela so svojím nanáhle shromaždeným vojskom vytiahnul z Pešti, vtedy Tatári ustupovali nazpät, pritiahnuc k sebe všetky svoje roztratené čaty, až ku rieke Šajave, kde cez stojáci most prešli na druhú stranu rieky a tam sa potom na rovine zastavili a do boja pripravili; keď toto všetko povážime, tedy to predsa nie pri osade Méhi, kde je rieka Šajava ešte nepatrná a dá sa ľahko prebrodiť, ale pri Onóde, neďaleko vtoku Šajave do Tisy, kde je rieka táto — súc spojená s Rimavou a Hornadom — hodne široká, udať sa muselo. Krem toho z Pešti nazpät ku Onódu cez Jáger bola im rovná, otvorená a ích tlupami všade obsadená cesta. Tam pri Onóde sa nachodily aj veliké močariny, ktoré na jar rozvodnená Tisa a Šajava robievala, aj" },
        { src: "/first try/img/beer.jpg", text: "Text pre oV dejepise sa menuje rovina Mohy pri Šajave, na ktorej sa tá bitka stala, a že na dolnej Šajave v Gemeri, neďaleko Šajo-Gemera, nachodí sa osada Méhi, ktorá s týmže menom má velikú podobnosť, a že tam na rovine sú aj značné pahŕbky plné umrlčích kostí, znakom velikej tam niekdy svedenej bitky: preto daktorí dejepisci túto bitku s Tatármi do Gemera ku osade Méhi kladú. Medzi tým, keď všetky okolnosti tej bitky dobre povážime, ako Tatári roku 5. panovania kráľa Belu, nasledovne už r. 1240 pod vedením Batu čili Batena v sile 500.000 vojska z ruskej zeme vtrhli do Uhár a najprv síce na hlavu porazili palatína, strážiaceho hranice 12. marca a všetko jeho vojsko strelami a mečmi pobili, ženúc sa prosto ku Pešti. Keď ale kráľ Bela so svojím nanáhle shromaždeným vojskom vytiahnul z Pešti, vtedy Tatári ustupovali nazpät, pritiahnuc k sebe všetky svoje roztratené čaty, až ku rieke Šajave, kde cez stojáci most prešli na druhú stranu rieky a tam sa potom na rovine zastavili a do boja pripravili; keď toto všetko povážime, tedy to predsa nie pri osade Méhi, kde je rieka Šajava ešte nepatrná a dá sa ľahko prebrodiť, ale pri Onóde, neďaleko vtoku Šajave do Tisy, kde je rieka táto — súc spojená s Rimavou a Hornadom — hodne široká, udať sa muselo. Krem toho z Pešti nazpät ku Onódu cez Jáger bola im rovná, otvorená a ích tlupami všade obsadená cesta. Tam pri Onóde sa nachodily aj veliké močariny, ktoré na jar rozvodnená Tisa a Šajava robievala, aj 6" },
        { src: "/first try/img/rehauL.png", text: "Text preV dejepise sa menuje rovina Mohy pri Šajave, na ktorej sa tá bitka stala, a že na dolnej Šajave v Gemeri, neďaleko Šajo-Gemera, nachodí sa osada Méhi, ktorá s týmže menom má velikú podobnosť, a že tam na rovine sú aj značné pahŕbky plné umrlčích kostí, znakom velikej tam niekdy svedenej bitky: preto daktorí dejepisci túto bitku s Tatármi do Gemera ku osade Méhi kladú. Medzi tým, keď všetky okolnosti tej bitky dobre povážime, ako Tatári roku 5. panovania kráľa Belu, nasledovne už r. 1240 pod vedením Batu čili Batena v sile 500.000 vojska z ruskej zeme vtrhli do Uhár a najprv síce na hlavu porazili palatína, strážiaceho hranice 12. marca a všetko jeho vojsko strelami a mečmi pobili, ženúc sa prosto ku Pešti. Keď ale kráľ Bela so svojím nanáhle shromaždeným vojskom vytiahnul z Pešti, vtedy Tatári ustupovali nazpät, pritiahnuc k sebe všetky svoje roztratené čaty, až ku rieke Šajave, kde cez stojáci most prešli na druhú stranu rieky a tam sa potom na rovine zastavili a do boja pripravili; keď toto všetko povážime, tedy to predsa nie pri osade Méhi, kde je rieka Šajava ešte nepatrná a dá sa ľahko prebrodiť, ale pri Onóde, neďaleko vtoku Šajave do Tisy, kde je rieka táto — súc spojená s Rimavou a Hornadom — hodne široká, udať sa muselo. Krem toho z Pešti nazpät ku Onódu cez Jáger bola im rovná, otvorená a ích tlupami všade obsadená cesta. Tam pri Onóde sa nachodily aj veliké močariny, ktoré na jar rozvodnená Tisa a Šajava robievala, ajok 7" },
        { src: "/first try/img/rehauKolege.jpg", text: "TexV dejepise sa menuje rovina Mohy pri Šajave, na ktorej sa tá bitka stala, a že na dolnej Šajave v Gemeri, neďaleko Šajo-Gemera, nachodí sa osada Méhi, ktorá s týmže menom má velikú podobnosť, a že tam na rovine sú aj značné pahŕbky plné umrlčích kostí, znakom velikej tam niekdy svedenej bitky: preto daktorí dejepisci túto bitku s Tatármi do Gemera ku osade Méhi kladú. Medzi tým, keď všetky okolnosti tej bitky dobre povážime, ako Tatári roku 5. panovania kráľa Belu, nasledovne už r. 1240 pod vedením Batu čili Batena v sile 500.000 vojska z ruskej zeme vtrhli do Uhár a najprv síce na hlavu porazili palatína, strážiaceho hranice 12. marca a všetko jeho vojsko strelami a mečmi pobili, ženúc sa prosto ku Pešti. Keď ale kráľ Bela so svojím nanáhle shromaždeným vojskom vytiahnul z Pešti, vtedy Tatári ustupovali nazpät, pritiahnuc k sebe všetky svoje roztratené čaty, až ku rieke Šajave, kde cez stojáci most prešli na druhú stranu rieky a tam sa potom na rovine zastavili a do boja pripravili; keď toto všetko povážime, tedy to predsa nie pri osade Méhi, kde je rieka Šajava ešte nepatrná a dá sa ľahko prebrodiť, ale pri Onóde, neďaleko vtoku Šajave do Tisy, kde je rieka táto — súc spojená s Rimavou a Hornadom — hodne široká, udať sa muselo. Krem toho z Pešti nazpät ku Onódu cez Jáger bola im rovná, otvorená a ích tlupami všade obsadená cesta. Tam pri Onóde sa nachodily aj veliké močariny, ktoré na jar rozvodnená Tisa a Šajava robievala, ajobrazok 8" },
        { src: "/first try/img/geberitL.png", text: "Text pV dejepise sa menuje rovina Mohy pri Šajave, na ktorej sa tá bitka stala, a že na dolnej Šajave v Gemeri, neďaleko Šajo-Gemera, nachodí sa osada Méhi, ktorá s týmže menom má velikú podobnosť, a že tam na rovine sú aj značné pahŕbky plné umrlčích kostí, znakom velikej tam niekdy svedenej bitky: preto daktorí dejepisci túto bitku s Tatármi do Gemera ku osade Méhi kladú. Medzi tým, keď všetky okolnosti tej bitky dobre povážime, ako Tatári roku 5. panovania kráľa Belu, nasledovne už r. 1240 pod vedením Batu čili Batena v sile 500.000 vojska z ruskej zeme vtrhli do Uhár a najprv síce na hlavu porazili palatína, strážiaceho hranice 12. marca a všetko jeho vojsko strelami a mečmi pobili, ženúc sa prosto ku Pešti. Keď ale kráľ Bela so svojím nanáhle shromaždeným vojskom vytiahnul z Pešti, vtedy Tatári ustupovali nazpät, pritiahnuc k sebe všetky svoje roztratené čaty, až ku rieke Šajave, kde cez stojáci most prešli na druhú stranu rieky a tam sa potom na rovine zastavili a do boja pripravili; keď toto všetko povážime, tedy to predsa nie pri osade Méhi, kde je rieka Šajava ešte nepatrná a dá sa ľahko prebrodiť, ale pri Onóde, neďaleko vtoku Šajave do Tisy, kde je rieka táto — súc spojená s Rimavou a Hornadom — hodne široká, udať sa muselo. Krem toho z Pešti nazpät ku Onódu cez Jáger bola im rovná, otvorená a ích tlupami všade obsadená cesta. Tam pri Onóde sa nachodily aj veliké močariny, ktoré na jar rozvodnená Tisa a Šajava robievala, ajazok 9" },
        { src: "/first try/img/gebe.jpg", text: "Text pre oV dejepise sa menuje rovina Mohy pri Šajave, na ktorej sa tá bitka stala, a že na dolnej Šajave v Gemeri, neďaleko Šajo-Gemera, nachodí sa osada Méhi, ktorá s týmže menom má velikú podobnosť, a že tam na rovine sú aj značné pahŕbky plné umrlčích kostí, znakom velikej tam niekdy svedenej bitky: preto daktorí dejepisci túto bitku s Tatármi do Gemera ku osade Méhi kladú. Medzi tým, keď všetky okolnosti tej bitky dobre povážime, ako Tatári roku 5. panovania kráľa Belu, nasledovne už r. 1240 pod vedením Batu čili Batena v sile 500.000 vojska z ruskej zeme vtrhli do Uhár a najprv síce na hlavu porazili palatína, strážiaceho hranice 12. marca a všetko jeho vojsko strelami a mečmi pobili, ženúc sa prosto ku Pešti. Keď ale kráľ Bela so svojím nanáhle shromaždeným vojskom vytiahnul z Pešti, vtedy Tatári ustupovali nazpät, pritiahnuc k sebe všetky svoje roztratené čaty, až ku rieke Šajave, kde cez stojáci most prešli na druhú stranu rieky a tam sa potom na rovine zastavili a do boja pripravili; keď toto všetko povážime, tedy to predsa nie pri osade Méhi, kde je rieka Šajava ešte nepatrná a dá sa ľahko prebrodiť, ale pri Onóde, neďaleko vtoku Šajave do Tisy, kde je rieka táto — súc spojená s Rimavou a Hornadom — hodne široká, udať sa muselo. Krem toho z Pešti nazpät ku Onódu cez Jáger bola im rovná, otvorená a ích tlupami všade obsadená cesta. Tam pri Onóde sa nachodily aj veliké močariny, ktoré na jar rozvodnená Tisa a Šajava robievala, aj 10" },
        { src: "/first try/img/gitHubLogo.jpg", text: "TextV dejepise sa menuje rovina Mohy pri Šajave, na ktorej sa tá bitka stala, a že na dolnej Šajave v Gemeri, neďaleko Šajo-Gemera, nachodí sa osada Méhi, ktorá s týmže menom má velikú podobnosť, a že tam na rovine sú aj značné pahŕbky plné umrlčích kostí, znakom velikej tam niekdy svedenej bitky: preto daktorí dejepisci túto bitku s Tatármi do Gemera ku osade Méhi kladú. Medzi tým, keď všetky okolnosti tej bitky dobre povážime, ako Tatári roku 5. panovania kráľa Belu, nasledovne už r. 1240 pod vedením Batu čili Batena v sile 500.000 vojska z ruskej zeme vtrhli do Uhár a najprv síce na hlavu porazili palatína, strážiaceho hranice 12. marca a všetko jeho vojsko strelami a mečmi pobili, ženúc sa prosto ku Pešti. Keď ale kráľ Bela so svojím nanáhle shromaždeným vojskom vytiahnul z Pešti, vtedy Tatári ustupovali nazpät, pritiahnuc k sebe všetky svoje roztratené čaty, až ku rieke Šajave, kde cez stojáci most prešli na druhú stranu rieky a tam sa potom na rovine zastavili a do boja pripravili; keď toto všetko povážime, tedy to predsa nie pri osade Méhi, kde je rieka Šajava ešte nepatrná a dá sa ľahko prebrodiť, ale pri Onóde, neďaleko vtoku Šajave do Tisy, kde je rieka táto — súc spojená s Rimavou a Hornadom — hodne široká, udať sa muselo. Krem toho z Pešti nazpät ku Onódu cez Jáger bola im rovná, otvorená a ích tlupami všade obsadená cesta. Tam pri Onóde sa nachodily aj veliké močariny, ktoré na jar rozvodnená Tisa a Šajava robievala, ajbrazok 11" },
        { src: "/first try/img/contact.jpg", text: "Text prV dejepise sa menuje rovina Mohy pri Šajave, na ktorej sa tá bitka stala, a že na dolnej Šajave v Gemeri, neďaleko Šajo-Gemera, nachodí sa osada Méhi, ktorá s týmže menom má velikú podobnosť, a že tam na rovine sú aj značné pahŕbky plné umrlčích kostí, znakom velikej tam niekdy svedenej bitky: preto daktorí dejepisci túto bitku s Tatármi do Gemera ku osade Méhi kladú. Medzi tým, keď všetky okolnosti tej bitky dobre povážime, ako Tatári roku 5. panovania kráľa Belu, nasledovne už r. 1240 pod vedením Batu čili Batena v sile 500.000 vojska z ruskej zeme vtrhli do Uhár a najprv síce na hlavu porazili palatína, strážiaceho hranice 12. marca a všetko jeho vojsko strelami a mečmi pobili, ženúc sa prosto ku Pešti. Keď ale kráľ Bela so svojím nanáhle shromaždeným vojskom vytiahnul z Pešti, vtedy Tatári ustupovali nazpät, pritiahnuc k sebe všetky svoje roztratené čaty, až ku rieke Šajave, kde cez stojáci most prešli na druhú stranu rieky a tam sa potom na rovine zastavili a do boja pripravili; keď toto všetko povážime, tedy to predsa nie pri osade Méhi, kde je rieka Šajava ešte nepatrná a dá sa ľahko prebrodiť, ale pri Onóde, neďaleko vtoku Šajave do Tisy, kde je rieka táto — súc spojená s Rimavou a Hornadom — hodne široká, udať sa muselo. Krem toho z Pešti nazpät ku Onódu cez Jáger bola im rovná, otvorená a ích tlupami všade obsadená cesta. Tam pri Onóde sa nachodily aj veliké močariny, ktoré na jar rozvodnená Tisa a Šajava robievala, ajzok 12" }
      ]
    },
    methods: {
      changeBackground() {
        
        document.body.style.background = "url('/first try/img/congruent.png')";
        document.body.style.backgroundSize = 'auto';
        document.body.style.backgroundAttachment = 'fixed';
        document.body.style.backgroundRepeat = 'repeat';
        document.body.style.height = 'auto';
        document.body.style.zIndex = 1;
  
        
        setTimeout(() => {
            this.showButton = false; 
            this.showProgress = true; 
        }, 1500); 
      },
      
      
    }
    }
  );
 